FROM mcr.microsoft.com/dotnet/aspnet:latest
ARG source
WORKDIR /app
EXPOSE 80

COPY bin/Release/net6.0/publish .

RUN apt-get update
RUN apt-get install -y gettext-base
RUN apt-get install -y dos2unix

RUN  dos2unix config.sh

ENTRYPOINT bash config.sh && echo homeautomation && dotnet homeautomation.dll