name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Publish
      run: dotnet publish --no-restore -c Release

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v1
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/service/Dockerfile
        push: true
        tags: fjordbob/homeautomation:latest      

  # docker:
  #     runs-on: ubuntu-latest
  #     needs: [build]
  #     steps:
  #       - name: Set up QEMU
  #         uses: docker/setup-qemu-action@v1
  #       - name: Set up Docker Buildx
  #         uses: docker/setup-buildx-action@v1
  #       - name: Login to DockerHub
  #         uses: docker/login-action@v1 
  #         with:
  #           username: ${{ secrets.DOCKER_USERNAME }}
  #           password: ${{ secrets.DOCKER_PAT }}
  #       - name: Build and push
  #         uses: docker/build-push-action@v2
  #         with:
  #           context: .
  #           file: homeautomation/src/service
  #           push: true
  #           tags: fjordbob/homeautomation:latest      
